[tools]
go = "1.25.6"
"go:github.com/air-verse/air" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"

[env]
GOBIN = "{{config_root}}/.bin"
"_.path" = "./.bin"

[tasks]
build = "go build -o bin/app ."
dev = "air"
lint = "go vet ./..."
